language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...
  - chmod +x ./scripts/coverage.sh

script:
  - go test  -coverprofile=profile.out -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
